.github/workflow: Debug missing protoc
Debug CI failure on missing protoc binary.

Caused by:
  process didn't exit successfully:
`/home/runner/work/rust-libp2p/rust-libp2p/target/debug/build/libp2p-core-31f9552cf2db9053/build-script-build`
(exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: Custom { kind: NotFound, error: "failed to invoke protoc (hint:
https://docs.rs/prost-build/#sourcing-protoc): No such file or directory
(os error 2)" }', core/build.rs:30:6