fix(muxers): import muxer-harness via path
`libp2p-muxer-harness` is never published to crates.io. Importing it as a workspace dependency makes
`cargo release` check crates.io for the there non-existing crate.

```
  Publishing libp2p-mplex
    Updating crates.io index
   Packaging libp2p-mplex v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/muxers/mplex)
   Verifying libp2p-mplex v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/muxers/mplex)
    Updating crates.io index
error: failed to verify package tarball

Caused by:
  no matching package named `libp2p-muxer-test-harness` found
  location searched: registry `crates-io`
  required by package `libp2p-mplex v0.40.0 (/home/mxinden/code/github.com/libp2p/rust-libp2p/target/package/libp2p-mplex-0.40.0)`
```

With this patch `libp2p-muxer-harness` is instead imported via `path` in `libp2p-yamux` and `libp2p-mplex`.